workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials
          # FCI_KEYSTORE: $FCI_KEYSTORE
          # FCI_KEYSTORE_PASSWORD: $FCI_KEYSTORE_PASSWORD
          # FCI_KEY_PASSWORD: $FCI_KEY_PASSWORD
          # FCI_KEY_ALIAS: $FCI_KEY_ALIAS
          # firebase_token: $FIREBASE_TOKEN
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
      #   PACKAGE_NAME: 'io.codemagic.himeshapp' # <-- Put your package name here
      #   GOOGLE_PLAY_TRACK: 'alpha' # <-- This must be "alpha" or above.
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up key properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          # The following script creates key.properties file and stores the credentials in it. As we configure code signing in app/build.gradle file, the following part is unnecessary unless code signing is configured differently as explained in the documentation: https://docs.codemagic.io/flutter-code-signing/android-code-signing/
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
          cd . && flutter analyze
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:391230974516:android:0c90036d3c5b25cb0df861
          groups:
            - androidTesters
